language: node_js
node_js:
  - '10'

cache:
  yarn: true

before_install:
  # upgrade Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test
  - yarn coveralls
